# Generated by Django 4.0.4 on 2023-02-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldiers', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('x_coordinate', models.IntegerField(default=0)),
                ('y_coordinate', models.IntegerField(default=0)),
                ('in_battle', models.BooleanField(default=False)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='captain.captain')),
            ],
        ),
    ]
